export default () => {
  const columns: any[] = [
    {
      id: 1094,
      name: '短信渠道',
      parentId: 1093,
      type: 2,
    },
    {
      id: 1118,
      name: '请假查询',
      parentId: 5,
      type: 2,
    },
    {
      id: 1138,
      name: '租户列表',
      parentId: 1224,
      type: 2,
    },
    {
      id: 1187,
      name: '流程表单',
      parentId: 1186,
      type: 2,
    },
    {
      id: 1201,
      name: '我的流程',
      parentId: 1200,
      type: 2,
    },
    {
      id: 1224,
      name: '租户管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 1225,
      name: '租户套餐',
      parentId: 1224,
      type: 2,
    },
    {
      id: 1237,
      name: '文件配置',
      parentId: 1243,
      type: 2,
    },
    {
      id: 1263,
      name: '应用管理',
      parentId: 1261,
      type: 2,
    },
    {
      id: 2131,
      name: '邮箱账号',
      parentId: 2130,
      type: 2,
    },
    {
      id: 2136,
      name: '邮件模版',
      parentId: 2130,
      type: 2,
    },
    {
      id: 2141,
      name: '邮件记录',
      parentId: 2130,
      type: 2,
    },
    {
      id: 2145,
      name: '模板管理',
      parentId: 2144,
      type: 2,
    },
    {
      id: 2151,
      name: '消息记录',
      parentId: 2144,
      type: 2,
    },
    {
      id: 100,
      name: '用户管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 115,
      name: '代码生成',
      parentId: 2,
      type: 2,
    },
    {
      id: 500,
      name: '操作日志',
      parentId: 108,
      type: 2,
    },
    {
      id: 1001,
      name: '用户查询',
      parentId: 100,
      type: 3,
    },
    {
      id: 1008,
      name: '角色查询',
      parentId: 101,
      type: 3,
    },
    {
      id: 1013,
      name: '菜单查询',
      parentId: 102,
      type: 3,
    },
    {
      id: 1017,
      name: '部门查询',
      parentId: 103,
      type: 3,
    },
    {
      id: 1021,
      name: '岗位查询',
      parentId: 104,
      type: 3,
    },
    {
      id: 1026,
      name: '字典查询',
      parentId: 105,
      type: 3,
    },
    {
      id: 1031,
      name: '配置查询',
      parentId: 106,
      type: 3,
    },
    {
      id: 1036,
      name: '公告查询',
      parentId: 107,
      type: 3,
    },
    {
      id: 1040,
      name: '操作查询',
      parentId: 500,
      type: 3,
    },
    {
      id: 1043,
      name: '登录查询',
      parentId: 501,
      type: 3,
    },
    {
      id: 1046,
      name: '令牌列表',
      parentId: 109,
      type: 3,
    },
    {
      id: 1066,
      name: '获得 Redis 监控信息',
      parentId: 113,
      type: 3,
    },
    {
      id: 1078,
      name: '访问日志',
      parentId: 1083,
      type: 2,
    },
    {
      id: 1087,
      name: '任务查询',
      parentId: 110,
      type: 3,
    },
    {
      id: 1088,
      name: '日志查询',
      parentId: 1078,
      type: 3,
    },
    {
      id: 1089,
      name: '日志查询',
      parentId: 1084,
      type: 3,
    },
    {
      id: 1091,
      name: '文件查询',
      parentId: 1090,
      type: 3,
    },
    {
      id: 1095,
      name: '短信渠道查询',
      parentId: 1094,
      type: 3,
    },
    {
      id: 1100,
      name: '短信模板',
      parentId: 1093,
      type: 2,
    },
    {
      id: 1101,
      name: '短信模板查询',
      parentId: 1100,
      type: 3,
    },
    {
      id: 1108,
      name: '短信日志查询',
      parentId: 1107,
      type: 3,
    },
    {
      id: 1111,
      name: '错误码查询',
      parentId: 1110,
      type: 3,
    },
    {
      id: 1119,
      name: '请假申请查询',
      parentId: 1118,
      type: 3,
    },
    {
      id: 1139,
      name: '租户查询',
      parentId: 1138,
      type: 3,
    },
    {
      id: 1188,
      name: '表单查询',
      parentId: 1187,
      type: 3,
    },
    {
      id: 1194,
      name: '模型查询',
      parentId: 1193,
      type: 3,
    },
    {
      id: 1202,
      name: '流程实例的查询',
      parentId: 1201,
      type: 3,
    },
    {
      id: 1210,
      name: '用户组查询',
      parentId: 1209,
      type: 3,
    },
    {
      id: 1221,
      name: '流程任务的查询',
      parentId: 1207,
      type: 3,
    },
    {
      id: 1226,
      name: '租户套餐查询',
      parentId: 1225,
      type: 3,
    },
    {
      id: 1238,
      name: '文件配置查询',
      parentId: 1237,
      type: 3,
    },
    {
      id: 1248,
      name: '敏感词查询',
      parentId: 1247,
      type: 3,
    },
    {
      id: 1255,
      name: '数据源配置',
      parentId: 2,
      type: 2,
    },
    {
      id: 1256,
      name: '数据源配置查询',
      parentId: 1255,
      type: 3,
    },
    {
      id: 1264,
      name: '客户端查询',
      parentId: 1263,
      type: 3,
    },
    {
      id: 2132,
      name: '账号查询',
      parentId: 2131,
      type: 3,
    },
    {
      id: 2137,
      name: '模版查询',
      parentId: 2136,
      type: 3,
    },
    {
      id: 2142,
      name: '日志查询',
      parentId: 2141,
      type: 3,
    },
    {
      id: 2146,
      name: '站内信模板查询',
      parentId: 2145,
      type: 3,
    },
    {
      id: 2152,
      name: '站内信消息查询',
      parentId: 2151,
      type: 3,
    },
    {
      id: 2448,
      name: '三方应用',
      parentId: 2447,
      type: 2,
    },
    {
      id: 2449,
      name: '三方应用查询',
      parentId: 2448,
      type: 3,
    },
    {
      id: 2527,
      name: '抄送流程查询',
      parentId: 2526,
      type: 3,
    },
    {
      id: 2584,
      name: '驾驶舱',
      parentId: 2583,
      type: 2,
    },
    {
      id: 2588,
      name: '菜单查询',
      parentId: 2591,
      type: 3,
    },
    {
      id: 2591,
      name: '菜单管理',
      parentId: 2586,
      type: 2,
    },
    {
      id: 2593,
      name: '信息管理',
      parentId: 2585,
      type: 2,
    },
    {
      id: 2598,
      name: '物料进场',
      parentId: 2597,
      type: 2,
    },
    {
      id: 2600,
      name: '工种查询',
      parentId: 2595,
      type: 3,
    },
    {
      id: 2606,
      name: '角色查询',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2609,
      name: '角色更新',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2622,
      name: '单位新增',
      parentId: 2596,
      type: 3,
    },
    {
      id: 2628,
      name: '用户查询',
      parentId: 2627,
      type: 3,
    },
    {
      id: 2635,
      name: '班组新增',
      parentId: 2613,
      type: 3,
    },
    {
      id: 2643,
      name: '证件新增',
      parentId: 2641,
      type: 3,
    },
    {
      id: 2644,
      name: '证件删除',
      parentId: 2641,
      type: 3,
    },
    {
      id: 2645,
      name: '证件修改',
      parentId: 2641,
      type: 3,
    },
    {
      id: 2646,
      name: '证件查询',
      parentId: 2641,
      type: 3,
    },
    {
      id: 2648,
      name: '单位管理',
      parentId: 2641,
      type: 2,
    },
    {
      id: 2651,
      name: '考勤汇总',
      parentId: 2650,
      type: 2,
    },
    {
      id: 101,
      name: '角色管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 109,
      name: '令牌管理',
      parentId: 1261,
      type: 2,
    },
    {
      id: 114,
      name: '表单构建',
      parentId: 2,
      type: 2,
    },
    {
      id: 501,
      name: '登录日志',
      parentId: 108,
      type: 2,
    },
    {
      id: 1002,
      name: '用户新增',
      parentId: 100,
      type: 3,
    },
    {
      id: 1009,
      name: '角色新增',
      parentId: 101,
      type: 3,
    },
    {
      id: 1014,
      name: '菜单新增',
      parentId: 102,
      type: 3,
    },
    {
      id: 1018,
      name: '部门新增',
      parentId: 103,
      type: 3,
    },
    {
      id: 1022,
      name: '岗位新增',
      parentId: 104,
      type: 3,
    },
    {
      id: 1027,
      name: '字典新增',
      parentId: 105,
      type: 3,
    },
    {
      id: 1032,
      name: '配置新增',
      parentId: 106,
      type: 3,
    },
    {
      id: 1037,
      name: '公告新增',
      parentId: 107,
      type: 3,
    },
    {
      id: 1042,
      name: '日志导出',
      parentId: 500,
      type: 3,
    },
    {
      id: 1048,
      name: '令牌删除',
      parentId: 109,
      type: 3,
    },
    {
      id: 1050,
      name: '任务新增',
      parentId: 110,
      type: 3,
    },
    {
      id: 1056,
      name: '生成修改',
      parentId: 115,
      type: 3,
    },
    {
      id: 1058,
      name: '导入代码',
      parentId: 115,
      type: 3,
    },
    {
      id: 1067,
      name: '获得 Redis Key 列表',
      parentId: 113,
      type: 3,
    },
    {
      id: 1082,
      name: '日志导出',
      parentId: 1078,
      type: 3,
    },
    {
      id: 1084,
      name: '错误日志',
      parentId: 1083,
      type: 2,
    },
    {
      id: 1085,
      name: '日志处理',
      parentId: 1084,
      type: 3,
    },
    {
      id: 1096,
      name: '短信渠道创建',
      parentId: 1094,
      type: 3,
    },
    {
      id: 1102,
      name: '短信模板创建',
      parentId: 1100,
      type: 3,
    },
    {
      id: 1107,
      name: '短信日志',
      parentId: 1093,
      type: 2,
    },
    {
      id: 1112,
      name: '错误码创建',
      parentId: 1110,
      type: 3,
    },
    {
      id: 1120,
      name: '请假申请创建',
      parentId: 1118,
      type: 3,
    },
    {
      id: 1140,
      name: '租户创建',
      parentId: 1138,
      type: 3,
    },
    {
      id: 1189,
      name: '表单创建',
      parentId: 1187,
      type: 3,
    },
    {
      id: 1195,
      name: '模型创建',
      parentId: 1193,
      type: 3,
    },
    {
      id: 1209,
      name: '用户分组',
      parentId: 1186,
      type: 2,
    },
    {
      id: 1211,
      name: '用户组创建',
      parentId: 1209,
      type: 3,
    },
    {
      id: 1219,
      name: '流程实例的创建',
      parentId: 1201,
      type: 3,
    },
    {
      id: 1222,
      name: '流程任务的更新',
      parentId: 1207,
      type: 3,
    },
    {
      id: 1227,
      name: '租户套餐创建',
      parentId: 1225,
      type: 3,
    },
    {
      id: 1239,
      name: '文件配置创建',
      parentId: 1237,
      type: 3,
    },
    {
      id: 1249,
      name: '敏感词创建',
      parentId: 1247,
      type: 3,
    },
    {
      id: 1257,
      name: '数据源配置创建',
      parentId: 1255,
      type: 3,
    },
    {
      id: 1265,
      name: '客户端创建',
      parentId: 1263,
      type: 3,
    },
    {
      id: 2133,
      name: '账号创建',
      parentId: 2131,
      type: 3,
    },
    {
      id: 2138,
      name: '模版创建',
      parentId: 2136,
      type: 3,
    },
    {
      id: 2147,
      name: '站内信模板创建',
      parentId: 2145,
      type: 3,
    },
    {
      id: 2450,
      name: '三方应用创建',
      parentId: 2448,
      type: 3,
    },
    {
      id: 2453,
      name: '三方用户',
      parentId: 2447,
      type: 2,
    },
    {
      id: 2528,
      name: '抄送流程创建',
      parentId: 2526,
      type: 3,
    },
    {
      id: 2585,
      name: '项目人员管理',
      parentId: 2583,
      type: 1,
    },
    {
      id: 2589,
      name: '菜单新建',
      parentId: 2591,
      type: 3,
    },
    {
      id: 2594,
      name: '信息采集',
      parentId: 2585,
      type: 2,
    },
    {
      id: 2599,
      name: '材料出场',
      parentId: 2597,
      type: 2,
    },
    {
      id: 2601,
      name: '工种新建',
      parentId: 2595,
      type: 3,
    },
    {
      id: 2605,
      name: '角色管理',
      parentId: 2586,
      type: 2,
    },
    {
      id: 2607,
      name: '角色新建',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2623,
      name: '单位修改',
      parentId: 2596,
      type: 3,
    },
    {
      id: 2629,
      name: '用户新增',
      parentId: 2627,
      type: 3,
    },
    {
      id: 2636,
      name: '班组删除',
      parentId: 2613,
      type: 3,
    },
    {
      id: 2652,
      name: '考勤明细',
      parentId: 2650,
      type: 2,
    },
    {
      id: 102,
      name: '菜单管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 116,
      name: '系统接口',
      parentId: 2,
      type: 2,
    },
    {
      id: 1003,
      name: '用户修改',
      parentId: 100,
      type: 3,
    },
    {
      id: 1010,
      name: '角色修改',
      parentId: 101,
      type: 3,
    },
    {
      id: 1015,
      name: '菜单修改',
      parentId: 102,
      type: 3,
    },
    {
      id: 1019,
      name: '部门修改',
      parentId: 103,
      type: 3,
    },
    {
      id: 1023,
      name: '岗位修改',
      parentId: 104,
      type: 3,
    },
    {
      id: 1028,
      name: '字典修改',
      parentId: 105,
      type: 3,
    },
    {
      id: 1033,
      name: '配置修改',
      parentId: 106,
      type: 3,
    },
    {
      id: 1038,
      name: '公告修改',
      parentId: 107,
      type: 3,
    },
    {
      id: 1045,
      name: '日志导出',
      parentId: 501,
      type: 3,
    },
    {
      id: 1051,
      name: '任务修改',
      parentId: 110,
      type: 3,
    },
    {
      id: 1057,
      name: '生成删除',
      parentId: 115,
      type: 3,
    },
    {
      id: 1086,
      name: '日志导出',
      parentId: 1084,
      type: 3,
    },
    {
      id: 1097,
      name: '短信渠道更新',
      parentId: 1094,
      type: 3,
    },
    {
      id: 1103,
      name: '短信模板更新',
      parentId: 1100,
      type: 3,
    },
    {
      id: 1113,
      name: '错误码更新',
      parentId: 1110,
      type: 3,
    },
    {
      id: 1141,
      name: '租户更新',
      parentId: 1138,
      type: 3,
    },
    {
      id: 1190,
      name: '表单更新',
      parentId: 1187,
      type: 3,
    },
    {
      id: 1196,
      name: '模型导入',
      parentId: 1193,
      type: 3,
    },
    {
      id: 1212,
      name: '用户组更新',
      parentId: 1209,
      type: 3,
    },
    {
      id: 1220,
      name: '流程实例的取消',
      parentId: 1201,
      type: 3,
    },
    {
      id: 1228,
      name: '租户套餐更新',
      parentId: 1225,
      type: 3,
    },
    {
      id: 1240,
      name: '文件配置更新',
      parentId: 1237,
      type: 3,
    },
    {
      id: 1250,
      name: '敏感词更新',
      parentId: 1247,
      type: 3,
    },
    {
      id: 1258,
      name: '数据源配置更新',
      parentId: 1255,
      type: 3,
    },
    {
      id: 1266,
      name: '客户端更新',
      parentId: 1263,
      type: 3,
    },
    {
      id: 2134,
      name: '账号更新',
      parentId: 2131,
      type: 3,
    },
    {
      id: 2139,
      name: '模版更新',
      parentId: 2136,
      type: 3,
    },
    {
      id: 2148,
      name: '站内信模板更新',
      parentId: 2145,
      type: 3,
    },
    {
      id: 2451,
      name: '三方应用更新',
      parentId: 2448,
      type: 3,
    },
    {
      id: 2587,
      name: '菜单删除',
      parentId: 2591,
      type: 3,
    },
    {
      id: 2597,
      name: '现场物料管理',
      parentId: 2583,
      type: 1,
    },
    {
      id: 2602,
      name: '工种删除',
      parentId: 2595,
      type: 3,
    },
    {
      id: 2608,
      name: '角色删除',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2624,
      name: '单位删除',
      parentId: 2596,
      type: 3,
    },
    {
      id: 2627,
      name: '用户管理',
      parentId: 2586,
      type: 2,
    },
    {
      id: 2630,
      name: '用户修改',
      parentId: 2627,
      type: 3,
    },
    {
      id: 2637,
      name: '班组修改',
      parentId: 2613,
      type: 3,
    },
    {
      id: 2641,
      name: '证件管理',
      parentId: 2585,
      type: 1,
    },
    {
      id: 2653,
      name: '考勤记录',
      parentId: 2650,
      type: 2,
    },
    {
      id: 103,
      name: '部门管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 1004,
      name: '用户删除',
      parentId: 100,
      type: 3,
    },
    {
      id: 1011,
      name: '角色删除',
      parentId: 101,
      type: 3,
    },
    {
      id: 1016,
      name: '菜单删除',
      parentId: 102,
      type: 3,
    },
    {
      id: 1020,
      name: '部门删除',
      parentId: 103,
      type: 3,
    },
    {
      id: 1024,
      name: '岗位删除',
      parentId: 104,
      type: 3,
    },
    {
      id: 1029,
      name: '字典删除',
      parentId: 105,
      type: 3,
    },
    {
      id: 1034,
      name: '配置删除',
      parentId: 106,
      type: 3,
    },
    {
      id: 1039,
      name: '公告删除',
      parentId: 107,
      type: 3,
    },
    {
      id: 1052,
      name: '任务删除',
      parentId: 110,
      type: 3,
    },
    {
      id: 1059,
      name: '预览代码',
      parentId: 115,
      type: 3,
    },
    {
      id: 1076,
      name: '数据库文档',
      parentId: 2,
      type: 2,
    },
    {
      id: 1092,
      name: '文件删除',
      parentId: 1090,
      type: 3,
    },
    {
      id: 1098,
      name: '短信渠道删除',
      parentId: 1094,
      type: 3,
    },
    {
      id: 1104,
      name: '短信模板删除',
      parentId: 1100,
      type: 3,
    },
    {
      id: 1114,
      name: '错误码删除',
      parentId: 1110,
      type: 3,
    },
    {
      id: 1142,
      name: '租户删除',
      parentId: 1138,
      type: 3,
    },
    {
      id: 1191,
      name: '表单删除',
      parentId: 1187,
      type: 3,
    },
    {
      id: 1197,
      name: '模型更新',
      parentId: 1193,
      type: 3,
    },
    {
      id: 1213,
      name: '用户组删除',
      parentId: 1209,
      type: 3,
    },
    {
      id: 1229,
      name: '租户套餐删除',
      parentId: 1225,
      type: 3,
    },
    {
      id: 1241,
      name: '文件配置删除',
      parentId: 1237,
      type: 3,
    },
    {
      id: 1251,
      name: '敏感词删除',
      parentId: 1247,
      type: 3,
    },
    {
      id: 1259,
      name: '数据源配置删除',
      parentId: 1255,
      type: 3,
    },
    {
      id: 1267,
      name: '客户端删除',
      parentId: 1263,
      type: 3,
    },
    {
      id: 2135,
      name: '账号删除',
      parentId: 2131,
      type: 3,
    },
    {
      id: 2140,
      name: '模版删除',
      parentId: 2136,
      type: 3,
    },
    {
      id: 2149,
      name: '站内信模板删除',
      parentId: 2145,
      type: 3,
    },
    {
      id: 2452,
      name: '三方应用删除',
      parentId: 2448,
      type: 3,
    },
    {
      id: 2590,
      name: '菜单更新',
      parentId: 2591,
      type: 3,
    },
    {
      id: 2604,
      name: '工种更新',
      parentId: 2595,
      type: 3,
    },
    {
      id: 2610,
      name: '角色导出',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2625,
      name: '单位查询',
      parentId: 2596,
      type: 3,
    },
    {
      id: 2631,
      name: '用户删除',
      parentId: 2627,
      type: 3,
    },
    {
      id: 2638,
      name: '班组查询',
      parentId: 2613,
      type: 3,
    },
    {
      id: 104,
      name: '岗位管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 1005,
      name: '用户导出',
      parentId: 100,
      type: 3,
    },
    {
      id: 1012,
      name: '角色导出',
      parentId: 101,
      type: 3,
    },
    {
      id: 1025,
      name: '岗位导出',
      parentId: 104,
      type: 3,
    },
    {
      id: 1030,
      name: '字典导出',
      parentId: 105,
      type: 3,
    },
    {
      id: 1035,
      name: '配置导出',
      parentId: 106,
      type: 3,
    },
    {
      id: 1053,
      name: '状态修改',
      parentId: 110,
      type: 3,
    },
    {
      id: 1060,
      name: '生成代码',
      parentId: 115,
      type: 3,
    },
    {
      id: 1090,
      name: '文件列表',
      parentId: 1243,
      type: 2,
    },
    {
      id: 1105,
      name: '短信模板导出',
      parentId: 1100,
      type: 3,
    },
    {
      id: 1109,
      name: '短信日志导出',
      parentId: 1107,
      type: 3,
    },
    {
      id: 1115,
      name: '错误码导出',
      parentId: 1110,
      type: 3,
    },
    {
      id: 1143,
      name: '租户导出',
      parentId: 1138,
      type: 3,
    },
    {
      id: 1192,
      name: '表单导出',
      parentId: 1187,
      type: 3,
    },
    {
      id: 1193,
      name: '流程模型',
      parentId: 1186,
      type: 2,
    },
    {
      id: 1198,
      name: '模型删除',
      parentId: 1193,
      type: 3,
    },
    {
      id: 1242,
      name: '文件配置导出',
      parentId: 1237,
      type: 3,
    },
    {
      id: 1243,
      name: '文件管理',
      parentId: 2,
      type: 2,
    },
    {
      id: 1252,
      name: '敏感词导出',
      parentId: 1247,
      type: 3,
    },
    {
      id: 1260,
      name: '数据源配置导出',
      parentId: 1255,
      type: 3,
    },
    {
      id: 2143,
      name: '发送测试邮件',
      parentId: 2136,
      type: 3,
    },
    {
      id: 2150,
      name: '发送测试站内信',
      parentId: 2145,
      type: 3,
    },
    {
      id: 2611,
      name: '字典查询',
      parentId: 2591,
      type: 3,
    },
    {
      id: 2612,
      name: '字典查询',
      parentId: 2594,
      type: 3,
    },
    {
      id: 2614,
      name: '设置角色菜单权限',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2617,
      name: '人员信息新增',
      parentId: 2594,
      type: 3,
    },
    {
      id: 2618,
      name: '人员信息查询',
      parentId: 2594,
      type: 3,
    },
    {
      id: 2619,
      name: '人员信息修改',
      parentId: 2594,
      type: 3,
    },
    {
      id: 2620,
      name: '人员信息删除',
      parentId: 2594,
      type: 3,
    },
    {
      id: 2632,
      name: '用户导出',
      parentId: 2627,
      type: 3,
    },
    {
      id: 2639,
      name: '班组导出',
      parentId: 2613,
      type: 3,
    },
    {
      id: 2640,
      name: '工种导出',
      parentId: 2595,
      type: 3,
    },
    {
      id: 2650,
      name: '考勤管理',
      parentId: 2585,
      type: 1,
    },
    {
      id: 105,
      name: '字典管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 106,
      name: '配置管理',
      parentId: 2,
      type: 2,
    },
    {
      id: 1006,
      name: '用户导入',
      parentId: 100,
      type: 3,
    },
    {
      id: 1063,
      name: '设置角色菜单权限',
      parentId: 101,
      type: 3,
    },
    {
      id: 1106,
      name: '发送测试短信',
      parentId: 1100,
      type: 3,
    },
    {
      id: 1199,
      name: '模型发布',
      parentId: 1193,
      type: 3,
    },
    {
      id: 2615,
      name: '设置角色数据权限',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2621,
      name: '工种信息查询',
      parentId: 2594,
      type: 3,
    },
    {
      id: 2633,
      name: '用户导入',
      parentId: 2627,
      type: 3,
    },
    {
      id: 1007,
      name: '重置密码',
      parentId: 100,
      type: 3,
    },
    {
      id: 1054,
      name: '任务导出',
      parentId: 110,
      type: 3,
    },
    {
      id: 1064,
      name: '设置角色数据权限',
      parentId: 101,
      type: 3,
    },
    {
      id: 2525,
      name: 'webSocket',
      parentId: 2,
      type: 2,
    },
    {
      id: 2595,
      name: '工种管理',
      parentId: 2585,
      type: 2,
    },
    {
      id: 2616,
      name: '设置用户角色',
      parentId: 2605,
      type: 3,
    },
    {
      id: 2634,
      name: '重置密码',
      parentId: 2627,
      type: 3,
    },
    {
      id: 107,
      name: '通知公告',
      parentId: 1,
      type: 2,
    },
    {
      id: 1065,
      name: '设置用户角色',
      parentId: 101,
      type: 3,
    },
    {
      id: 1075,
      name: '任务触发',
      parentId: 110,
      type: 3,
    },
    {
      id: 1083,
      name: 'API 日志',
      parentId: 2,
      type: 2,
    },
    {
      id: 2596,
      name: '单位管理',
      parentId: 2585,
      type: 2,
    },
    {
      id: 108,
      name: '审计日志',
      parentId: 1,
      type: 1,
    },
    {
      id: 111,
      name: 'MySQL 监控',
      parentId: 2,
      type: 2,
    },
    {
      id: 2613,
      name: '班组管理',
      parentId: 2585,
      type: 2,
    },
    {
      id: 1,
      name: '系统管理',
      parentId: 0,
      type: 1,
    },
    {
      id: 113,
      name: 'Redis 监控',
      parentId: 2,
      type: 2,
    },
    {
      id: 1186,
      name: '流程管理',
      parentId: 1185,
      type: 1,
    },
    {
      id: 1207,
      name: '待办任务',
      parentId: 1200,
      type: 2,
    },
    {
      id: 1215,
      name: '流程定义查询',
      parentId: 1193,
      type: 3,
    },
    {
      id: 1261,
      name: 'OAuth 2.0',
      parentId: 1,
      type: 1,
    },
    {
      id: 2447,
      name: '三方登录',
      parentId: 1,
      type: 1,
    },
    {
      id: 2586,
      name: '系统管理',
      parentId: 2583,
      type: 1,
    },
    {
      id: 112,
      name: 'Java 监控',
      parentId: 2,
      type: 2,
    },
    {
      id: 1093,
      name: '短信管理',
      parentId: 1,
      type: 1,
    },
    {
      id: 2130,
      name: '邮箱管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 2144,
      name: '站内信管理',
      parentId: 1,
      type: 1,
    },
    {
      id: 110,
      name: '定时任务',
      parentId: 2,
      type: 2,
    },
    {
      id: 1110,
      name: '错误码管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 1247,
      name: '敏感词管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 2083,
      name: '地区管理',
      parentId: 1,
      type: 2,
    },
    {
      id: 2,
      name: '基础设施',
      parentId: 0,
      type: 1,
    },
    {
      id: 1200,
      name: '任务管理',
      parentId: 1185,
      type: 1,
    },
    {
      id: 1208,
      name: '已办任务',
      parentId: 1200,
      type: 2,
    },
    {
      id: 1216,
      name: '流程任务分配规则查询',
      parentId: 1193,
      type: 3,
    },
    {
      id: 1217,
      name: '流程任务分配规则创建',
      parentId: 1193,
      type: 3,
    },
    {
      id: 2526,
      name: '抄送流程',
      parentId: 1200,
      type: 2,
    },
    {
      id: 1218,
      name: '流程任务分配规则更新',
      parentId: 1193,
      type: 3,
    },
    {
      id: 5,
      name: 'OA 示例',
      parentId: 1185,
      type: 1,
    },
    {
      id: 1185,
      name: '工作流程',
      parentId: 0,
      type: 1,
    },
    {
      id: 2583,
      name: '华光智慧监管平台',
      parentId: 0,
      type: 1,
    },
    {
      id: 2654,
      name: '组件展示',
      parentId: 2583,
      type: 2,
    },
  ];

  return columns;
};
