import { ApiItem } from '@spms/web-request';
const ADMIN_API = import.meta.env.VITE_APP_ADMIN_API;

const job: ApiItem[] = [
  {
    key: 'getJobList',
    url: `${ADMIN_API}/wisdom/work-type-info/page`,
    type: 'GET',
    name: '工种管理',
    description: '获取工种列表',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'code', cn: '编号' },
      { key: 'name', cn: '工种' },
      { key: 'initialsSpell', cn: '首字母简拼' },
      { key: 'isSpecialWorkType', cn: '是否特殊工种' },
    ],
  },
  {
    key: 'createJob',
    url: `${ADMIN_API}/wisdom/work-type-info/create`,
    type: 'POST',
    name: '工种管理',
    description: '新建工种',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'code', cn: '编号' },
      { key: 'name', cn: '工种' },
      { key: 'initialsSpell', cn: '首字母简拼' },
      { key: 'isSpecialWorkType', cn: '是否特殊工种' },
      { key: 'sort', cn: '排序' },
    ],
  },
  {
    key: 'updateJob',
    url: `${ADMIN_API}/wisdom/work-type-info/update`,
    type: 'PATCH',
    name: '工种管理',
    description: '编辑工种信息',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'code', cn: '编号' },
      { key: 'name', cn: '工种' },
      { key: 'initialsSpell', cn: '首字母简拼' },
      { key: 'isSpecialWorkType', cn: '是否特殊工种' },
      { key: 'sort', cn: '排序' },
    ],
  },
  {
    key: 'getSubContractorList',
    url: `${ADMIN_API}/wisdom/subcontractor-info/page`,
    type: 'GET',
    name: '分包商管理',
    description: '获取分包商列表',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'realName', cn: '分包商名称' },
      { key: 'subcontractorType', cn: '分包商类型' },
    ],
  },
  {
    key: 'createSubContractor',
    url: `${ADMIN_API}/wisdom/subcontractor-info/create`,
    type: 'POST',
    name: '分包商管理',
    description: '新建分包商',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'realName', cn: '分包商名称' },
      { key: 'shortName', cn: '分包商简称' },
      { key: 'subcontractorType', cn: '分包商类型' },
      { key: 'province', cn: '所属省' },
      { key: 'city', cn: '所属市' },
      { key: 'district', cn: '所属区' },
      { key: 'corpType', cn: '参建单位类型' },
      { key: 'overallMerit', cn: '等级' },
      { key: 'isConformity', cn: '是否生效' },
      { key: 'unitAddress', cn: '单位地址' },
      { key: 'legalRepresentative', cn: '法人' },
      { key: 'legalRepresentativePhone', cn: '法人联系电话' },
      { key: 'registeredCapital', cn: '注册资金(万元)' },
      { key: 'regDate', cn: '注册时间' },
      { key: 'principal', cn: '联系人' },
      { key: 'principalTel', cn: '联系电话' },
      { key: 'idCard', cn: '联系人身份证号' },
      { key: 'quality', cn: '资质' },
      { key: 'nameSpell', cn: '公司简称简拼' },
      { key: 'corpCode', cn: '社会信用代码' },
      { key: 'buildComplaintCall', cn: '住建部投诉电话' },
      { key: 'societyComplaintCall', cn: '人社部投诉电话' },
      { key: 'companyScore', cn: '公司项目经验' },
      { key: 'companySummary', cn: '公司简介' },
    ],
  },
  {
    key: 'updateJob',
    url: `${ADMIN_API}/wisdom/subcontractor-info/update`,
    type: 'PUT',
    name: '分包商管理',
    description: '编辑分包商',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'realName', cn: '分包商名称' },
      { key: 'subcontractorType', cn: '分包商类型' },
      { key: 'corpCode', cn: '社会信用代码' },
      { key: 'legalRepresentative', cn: '法人' },
      { key: 'registeredCapital', cn: '注册资金(万元)' },
      { key: 'unitAddress', cn: '单位地址' },
      { key: 'principal', cn: '联系人' },
      { key: 'principalTel', cn: '联系电话' },
      { key: 'nameSpell', cn: '公司简称简拼' },
    ],
  },
];
export default job;
