import { ApiItem } from '@spms/web-request';

const ADMIN_API = import.meta.env.VITE_APP_ADMIN_API;

const materialList: ApiItem[] = [
  {
    key: 'getFirstList',
    url: `${ADMIN_API}/wisdom/materials-first-inventory/page`,
    type: 'GET',
    name: '一级物料列表',
    description: '获取一级物料列表',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'createGroup',
    url: `${ADMIN_API}/wisdom/group-info/create`,
    type: 'POST',
    name: '班组管理',
    description: '新建班组',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'userId', cn: '班组长id' },
      { key: 'teamName', cn: '班组名称' },
      { key: 'subcontractorId', cn: '分包单位id' },
      { key: 'workTypeName', cn: '劳务工种' },
      { key: 'identityCard', cn: '身份证号' },
      { key: 'phone', cn: '联系方式' },
      { key: 'entryDate', cn: '进场时间' },
      { key: 'exitDate', cn: '退场时间' },
      { key: 'entryAttachments', cn: '进场附件' },
      { key: 'exitAttachments', cn: '退场附件' },
    ],
  },
  {
    key: 'updateFirst',
    url: `${ADMIN_API}/wisdom/materials-first-inventory/update`,
    type: 'PUT',
    name: '一级物料列表',
    description: '编辑一级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'firstLevelName', cn: '一级物料名称' },
    ],
  },
  {
    key: 'deleteGroup',
    url: `${ADMIN_API}/wisdom/group-info/delete`,
    type: 'DELETE',
    name: '班组管理',
    description: '删除班组',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
    ],
  },
  {
    key: 'getSecondList',
    url: `${ADMIN_API}/wisdom/materials-second-inventory/page`,
    type: 'GET',
    name: '二级物料列表',
    description: '获取二级物料列表',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'firstLevelCode', cn: '一级物料编码' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'updateSecond',
    url: `${ADMIN_API}/wisdom/materials-second-inventory/update`,
    type: 'PUT',
    name: '二级物料列表',
    description: '编辑二级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'secondLevelName', cn: '二级物料名称' },
    ],
  },
  {
    key: 'getThirdList',
    url: `${ADMIN_API}/wisdom/materials-third-inventory/page`,
    type: 'GET',
    name: '三级物料列表',
    description: '获取三级物料列表',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'secondLevelCode', cn: '二级物料编码' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'updateThird',
    url: `${ADMIN_API}/wisdom/materials-third-inventory/update`,
    type: 'PUT',
    name: '三级物料列表',
    description: '编辑三级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'thirdLevelName', cn: '三级物料名称' },
    ],
  },
  {
    key: 'getMaterialList',
    url: `${ADMIN_API}/wisdom/materials-inventory/page`,
    type: 'GET',
    name: '物料清单列表',
    description: '获取物料清单列表',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'thirdLevelCode', cn: '三级物料编码' },
      { key: 'materialName', cn: '材料名称' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'updateMaterial',
    url: `${ADMIN_API}/wisdom/materials-inventory/update`,
    type: 'PUT',
    name: '物料清单列表',
    description: '编辑物料清单',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'materialName', cn: '材料名称' },
      { key: 'specification', cn: '规格' },
      { key: 'measuringUnit', cn: '计量单位' },
      { key: 'price', cn: '价格' },
      { key: 'remark', cn: '备注' },
      { key: 'description', cn: '说明' },
      { key: 'initialEightBitCode', cn: '初始八位码' },
      { key: 'originalSixBitCode', cn: '原六位码' },
      { key: 'originalProvinceTenBitCode', cn: '原省十位码' },
    ],
  },
];
export default materialList;
