import { ApiItem } from '@spms/web-request';

const ADMIN_API = import.meta.env.VITE_APP_ADMIN_API;

const materialList: ApiItem[] = [
  {
    key: 'getFirstList',
    url: `${ADMIN_API}/wisdom/materials-first-inventory/page`,
    type: 'GET',
    name: '一级物料列表',
    description: '获取一级物料列表(分页)',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'getAllFirstList',
    url: `${ADMIN_API}/wisdom/materials-first-inventory/list`,
    type: 'GET',
    name: '一级物料列表',
    description: '获取一级物料列表(不分页)',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'firstLevelName', cn: '一级物料名称' },
    ],
  },
  {
    key: 'updateFirst',
    url: `${ADMIN_API}/wisdom/materials-first-inventory/update`,
    type: 'PUT',
    name: '一级物料列表',
    description: '编辑一级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'firstLevelName', cn: '一级物料名称' },
    ],
  },
  {
    key: 'createFirst',
    url: `${ADMIN_API}/wisdom/materials-first-inventory/create`,
    type: 'POST',
    name: '一级物料列表',
    description: '新增一级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      {
        key: 'levelCode',
        targetKey: 'firstLevelCode',
        cn: '一级物料编码',
      },
      {
        key: 'levelName',
        targetKey: 'firstLevelName',
        cn: '一级物料名称',
      },
    ],
  },
  {
    key: 'getSecondList',
    url: `${ADMIN_API}/wisdom/materials-second-inventory/page`,
    type: 'GET',
    name: '二级物料列表',
    description: '获取二级物料列表(分页)',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'firstLevelCode', cn: '一级物料编码' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'getAllSecondList',
    url: `${ADMIN_API}/wisdom/materials-second-inventory/list-by-first`,
    type: 'GET',
    name: '二级物料列表',
    description: '获取二级物料列表(不分页)',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'firstLevelCode', cn: '一级物料编码' },
      { key: 'secondLevelName', cn: '二级物料名称' },
    ],
  },
  {
    key: 'updateSecond',
    url: `${ADMIN_API}/wisdom/materials-second-inventory/update`,
    type: 'PUT',
    name: '二级物料列表',
    description: '编辑二级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'secondLevelName', cn: '二级物料名称' },
    ],
  },
  {
    key: 'createSecond',
    url: `${ADMIN_API}/wisdom/materials-second-inventory/create`,
    type: 'POST',
    name: '二级物料列表',
    description: '新增二级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'firstLevelCode', cn: '一级物料编码' },
      {
        key: 'levelCode',
        targetKey: 'secondLevelCode',
        cn: '二级物料编码',
      },
      {
        key: 'levelName',
        targetKey: 'secondLevelName',
        cn: '二级物料名称',
      },
    ],
  },
  {
    key: 'getThirdList',
    url: `${ADMIN_API}/wisdom/materials-third-inventory/page`,
    type: 'GET',
    name: '三级物料列表',
    description: '获取三级物料列表',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'secondLevelCode', cn: '二级物料编码' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'updateThird',
    url: `${ADMIN_API}/wisdom/materials-third-inventory/update`,
    type: 'PUT',
    name: '三级物料列表',
    description: '编辑三级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'thirdLevelName', cn: '三级物料名称' },
    ],
  },
  {
    key: 'createThird',
    url: `${ADMIN_API}/wisdom/materials-third-inventory/create`,
    type: 'POST',
    name: '三级物料列表',
    description: '新增三级物料',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'secondLevelCode', cn: '二级物料编码' },
      {
        key: 'levelCode',
        targetKey: 'thirdLevelCode',
        cn: '三级物料编码',
      },
      {
        key: 'levelName',
        targetKey: 'thirdLevelName',
        cn: '三级物料名称',
      },
    ],
  },
  {
    key: 'getMaterialList',
    url: `${ADMIN_API}/wisdom/materials-inventory/page`,
    type: 'GET',
    name: '物料清单列表',
    description: '获取物料清单列表(分页)',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'thirdLevelCode', cn: '三级物料编码' },
      { key: 'materialName', cn: '材料名称' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'getAllMaterialList',
    url: `${ADMIN_API}/wisdom/materials-inventory/list`,
    type: 'GET',
    name: '物料清单列表',
    description: '获取物料清单列表(不分页)',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'materialName', cn: '材料名称' },
      { key: 'materialCode', cn: '材料编码' },
    ],
  },
  {
    key: 'getMaterialDetail',
    url: `${ADMIN_API}/wisdom/materials-inventory/get`,
    type: 'GET',
    name: '物料清单列表',
    description: '获取物料清单详情',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
    ],
  },
  {
    key: 'updateMaterial',
    url: `${ADMIN_API}/wisdom/materials-inventory/update`,
    type: 'PUT',
    name: '物料清单列表',
    description: '编辑物料清单',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'materialName', cn: '材料名称' },
      { key: 'specification', cn: '规格' },
      { key: 'measuringUnit', cn: '计量单位' },
      { key: 'price', cn: '价格' },
      { key: 'remark', cn: '备注' },
      { key: 'description', cn: '说明' },
      { key: 'initialEightBitCode', cn: '初始八位码' },
      { key: 'originalSixBitCode', cn: '原六位码' },
      { key: 'originalProvinceTenBitCode', cn: '原省十位码' },
    ],
  },
  {
    key: 'createMaterial',
    url: `${ADMIN_API}/wisdom/materials-inventory/create`,
    type: 'POST',
    name: '物料清单列表',
    description: '新增物料清单',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'thirdLevelCode', cn: '三级物料编码' },
      { key: 'materialCode', cn: '材料编码' },
      { key: 'materialName', cn: '材料名称' },
      { key: 'specification', cn: '规格' },
      { key: 'measuringUnit', cn: '计量单位' },
      { key: 'price', cn: '价格' },
      { key: 'remark', cn: '备注' },
      { key: 'description', cn: '说明' },
      { key: 'initialEightBitCode', cn: '初始八位码' },
      { key: 'originalSixBitCode', cn: '原六位码' },
      { key: 'originalProvinceTenBitCode', cn: '原省十位码' },
    ],
  },
  {
    key: 'analysisList',
    url: `${ADMIN_API}/wisdom/materials-enter/analyse-page`,
    type: 'GET',
    name: '物料智能分析',
    description: '列表查询',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'carNo', cn: '车牌号' },
      { key: 'beginTime', cn: '称重时间' },
      { key: 'endTime', cn: '称重时间' },
    ],
  },
  {
    key: 'deleteFirst',
    url: `${ADMIN_API}/wisdom/materials-first-inventory/delete`,
    type: 'DELETE',
    name: '删除一级类别',
    description: '删除一级类别',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: 'id' },
 
    ],
  },
  {
    key: 'deleteSecond',
    url: `${ADMIN_API}/wisdom/materials-second-inventory/delete`,
    type: 'DELETE',
    name: '删除二级类别',
    description: '删除二级类别',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: 'id' },
 
    ],
  },
  {
    key: 'deleteThird',
    url: `${ADMIN_API}/wisdom/materials-third-inventory/delete`,
    type: 'DELETE',
    name: '删除三级类别',
    description: '删除三级类别',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: 'id' },
 
    ],
  },
];
export default materialList;
