import { ApiItem } from '@spms/web-request';
const ADMIN_API = import.meta.env.VITE_APP_ADMIN_API;

const subContractor: ApiItem[] = [
  {
    key: 'getSubContractorList',
    url: `${ADMIN_API}/wisdom/subcontractor-info/page`,
    type: 'GET',
    name: '单位管理',
    description: '获取单位列表(分页)',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'realName', cn: '单位名称' },
      { key: 'subcontractorType', cn: '单位类型' },
      { key: 'current', targetKey: 'pageNo' },
      { key: 'pageSize' },
    ],
  },
  {
    key: 'getAllSubContractor',
    url: `${ADMIN_API}/wisdom/subcontractor-info/list`,
    type: 'GET',
    name: '单位管理',
    description: '获取单位列表(不分页)',
    params: [{ key: 'Authorization', location: 'header' }],
  },
  {
    key: 'getSubContractorDetail',
    url: `${ADMIN_API}/wisdom/subcontractor-info/get`,
    type: 'GET',
    name: '单位管理',
    description: '获取单位详情',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '所属市' },
    ],
  },
  {
    key: 'createSubContractor',
    url: `${ADMIN_API}/wisdom/subcontractor-info/create`,
    type: 'POST',
    name: '单位管理',
    description: '新建单位',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'realName', cn: '单位名称' },
      { key: 'shortName', cn: '单位简称' },
      { key: 'subcontractorType', cn: '单位类型' },
      { key: 'province', cn: '所属省' },
      { key: 'city', cn: '所属市' },
      { key: 'district', cn: '所属区' },
      { key: 'corpType', cn: '参建单位类型' },
      { key: 'overallMerit', cn: '等级' },
      { key: 'isConformity', cn: '是否生效' },
      { key: 'unitAddress', cn: '单位地址' },
      { key: 'legalRepresentative', cn: '法人' },
      { key: 'legalRepresentativePhone', cn: '法人联系电话' },
      { key: 'registeredCapital', cn: '注册资金(万元)' },
      { key: 'regDate', cn: '注册时间' },
      { key: 'principal', cn: '联系人' },
      { key: 'principalTel', cn: '联系电话' },
      { key: 'idCard', cn: '联系人身份证号' },
      { key: 'quality', cn: '资质' },
      { key: 'nameSpell', cn: '公司简称简拼' },
      { key: 'corpCode', cn: '社会信用代码' },
      { key: 'buildComplaintCall', cn: '住建部投诉电话' },
      { key: 'societyComplaintCall', cn: '人社部投诉电话' },
      { key: 'companyScore', cn: '公司项目经验' },
      { key: 'companySummary', cn: '公司简介' },
    ],
  },
  {
    key: 'updateSubContractor',
    url: `${ADMIN_API}/wisdom/subcontractor-info/update`,
    type: 'PUT',
    name: '单位管理',
    description: '编辑单位',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
      { key: 'realName', cn: '单位名称' },
      { key: 'shortName', cn: '单位简称' },
      { key: 'subcontractorType', cn: '单位类型' },
      { key: 'province', cn: '所属省' },
      { key: 'city', cn: '所属市' },
      { key: 'district', cn: '所属区' },
      { key: 'corpType', cn: '参建单位类型' },
      { key: 'overallMerit', cn: '等级' },
      { key: 'isConformity', cn: '是否生效' },
      { key: 'unitAddress', cn: '单位地址' },
      { key: 'legalRepresentative', cn: '法人' },
      { key: 'legalRepresentativePhone', cn: '法人联系电话' },
      { key: 'registeredCapital', cn: '注册资金(万元)' },
      { key: 'regDate', cn: '注册时间' },
      { key: 'principal', cn: '联系人' },
      { key: 'principalTel', cn: '联系电话' },
      { key: 'idCard', cn: '联系人身份证号' },
      { key: 'quality', cn: '资质' },
      { key: 'nameSpell', cn: '公司简称简拼' },
      { key: 'corpCode', cn: '社会信用代码' },
      { key: 'buildComplaintCall', cn: '住建部投诉电话' },
      { key: 'societyComplaintCall', cn: '人社部投诉电话' },
      { key: 'companyScore', cn: '公司项目经验' },
      { key: 'companySummary', cn: '公司简介' },
    ],
  },
  {
    key: 'deleteSubContractor',
    url: `${ADMIN_API}/wisdom/subcontractor-info/delete`,
    type: 'DELETE',
    name: '单位管理',
    description: '编辑单位',
    params: [
      { key: 'Authorization', location: 'header' },
      { key: 'id', cn: '数据库主键' },
    ],
  },
];
export default subContractor;
